_wandb:
    value:
        cli_version: 0.22.3
        e:
            rtk2zt0vh8tks9vitjo4h14whwicmwj8:
                args:
                    - --mode
                    - classifier
                    - --pretrained_simclr
                    - simclr_vit.pth
                    - --batch_size
                    - "128"
                    - --epochs
                    - "10"
                    - --num_workers
                    - "0"
                    - --wandb
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "511401943040"
                        used: "364572549120"
                email: milosz.adamczyk2002@gmail.com
                executable: C:\Users\Milosz\anaconda3\envs\URWGSN\python.exe
                gpu: NVIDIA GeForce GTX 1650 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 Ti
                      uuid: GPU-969486da-44e4-ee14-483a-09654cfbc580
                host: DESKTOP-UM6MBAK
                memory:
                    total: "17002713088"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\Milosz\Desktop\PR2\Lab2\train.py
                python: CPython 3.12.12
                root: C:\Users\Milosz\Desktop\PR2\Lab2
                startedAt: "2025-11-03T21:07:19.214264Z"
                writerId: rtk2zt0vh8tks9vitjo4h14whwicmwj8
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 128
epochs:
    value: 10
lr:
    value: 0.0003
mode:
    value: classifier
